### ISSUE TITLE
Snapenhance Keeps Stopping (Latest CI) 

### ISSUE THREAD

**Issue by fgjaee** [rhunk/SnapEnhance#1091]
### Description

SnapEnhance Randomly stops and crashes Snapchat too. This is with the latest CI of snapenhance and snapchat version 12.81

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs

```markdown
|V/2024-05-31 11:33:18/manager/Loading RemoteSideContext
|V/2024-05-31 11:33:19/core/reloading config
|E/2024-05-31 11:33:19/core/Failed to get custom emoji font
|E/2024-05-31 11:33:19/core/java.io.IOException: read failed: EISDIR (Is a directory)
	at libcore.io.IoBridge.read(IoBridge.java:614)
	at java.io.FileInputStream.read(FileInputStream.java:328)
	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:1032)
	at java.io.FileInputStream.read(FileInputStream.java:297)
	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:1023)
	at com.google.common.primitives.b.U(Unknown Source:12)
	at me.rhunk.snapenhance.core.util.ktx.FileHandleManagerKtxKt.getFileHandleLocalPath(Unknown Source:134)
	at me.rhunk.snapenhance.core.features.impl.experiments.CustomEmojiFontKt.getCustomEmojiFontPath(Unknown Source:47)
	at me.rhunk.snapenhance.core.ModContext.reloadNativeConfig(Unknown Source:101)
	at me.rhunk.snapenhance.core.ModContext.reloadConfig(Unknown Source:18)
	at me.rhunk.snapenhance.core.SnapEnhance.init(Unknown Source:19)
	at me.rhunk.snapenhance.core.SnapEnhance.access$init(Unknown Source:0)
	at me.rhunk.snapenhance.core.SnapEnhance$1$2$1$2$3$1$1.invokeSuspend(Unknown Source:15)
	at t2.a.resumeWith(Unknown Source:8)
	at N2.H.run(Unknown Source:114)
	at N2.S.U(Unknown Source:138)
	at com.google.common.primitives.b.G1(Unknown Source:104)
	at com.google.common.primitives.b.H1(Unknown Source:2)
	at me.rhunk.snapenhance.core.SnapEnhance$1$2$1$2.invoke(SourceFile:9)
	at me.rhunk.snapenhance.core.SnapEnhance$1$2$1$2.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.bridge.BridgeClient.connect(Unknown Source:159)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:7)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:180)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1302)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1545)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1463)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7525)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2416)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8825)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: android.system.ErrnoException: read failed: EISDIR (Is a directory)
	at libcore.io.Linux.readBytes(Native Method)
	at libcore.io.Linux.read(Linux.java:190)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:613)
	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:325)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:613)
	at libcore.io.IoBridge.read(IoBridge.java:604)
	... 39 more

|V/2024-05-31 11:33:19/manager/Syncing remote took 1 ms
|V/2024-05-31 11:33:19/core/database main.db integrity check passed
|V/2024-05-31 11:33:19/core/database arroyo.db integrity check passed
|W/2024-05-31 11:33:19/core/Failed to find ANDROID_ACTION_MENU_V2 in ConfigRule
|V/2024-05-31 11:33:19/core/feature manager init took 50 ms
|V/2024-05-31 11:33:19/core/init took 563ms
|D/2024-05-31 11:33:31/manager/Saving logs, this may take a while ...
```

### Snapchat Version

12.81

### SnapEnhance Version

2.1.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by fgjaee** [comment]
> [5d5a067](https://github.com/rhunk/SnapEnhance/commit/5d5a067319df31d56d5e9b3d1612f47c3af160ab) [8ca4cd6](https://github.com/rhunk/SnapEnhance/commit/8ca4cd6995735592d472fe1849af41c74e28f641)

Thanks,

You releasing a new apk soon?
