### ISSUE TITLE
...

### ISSUE THREAD

**Issue by itsgillani** [rhunk/SnapEnhance#1120]
### Description

The error message says:
"Snapchat cant connect to the SnapEnhance app/ Make sure you have the latest version installed on your device. You can download the latest stable version on github/com/rhunk/SnapEnhance."

Temporary Fix:
''After this error pops up when i manually open SnapEnhance App for upto 4-5 seconds and opening/closing snapchat for 2-3 times then the SnapEnhance module works flawlessly in snapchat''.

For your clearance I have already removed SnapEnhanced from battery optimization

### Reproduction steps

1. Open SnapChat after Phone has not been used since a long time.
2. After some time the given error pops up.

### Logs

```markdown
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1936)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2071)
	at me.rhunk.snapenhance.core.bridge.BridgeClient.connect(Unknown Source:150)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:7)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1233)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7024)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2207)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
```

### Snapchat Version

12.89.0.40

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
...

**Comment by authorisation** [comment]
#1118
