### ISSUE TITLE
Lspatch issue

### ISSUE THREAD

**Issue by kittenvr** [rhunk/SnapEnhance#1149]
### Description

When install I get error

### Reproduction steps

1. Go to lepatch
2. Do the install instructions 
3. See error

### Logs

```markdown
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1936)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2071)
	at me.rhunk.snapenhance.core.bridge.BridgeClient.connect(Unknown Source:150)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:7)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1283)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1512)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1449)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7625)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Snapchat Version

12.92.0.48

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by Paywandako** [comment]
What phone are you using? and is the system ROM native or custom?

**Comment by Paywandako** [comment]
Don't install, it's not safe yet. The last patch was detected

**Comment by kittenvr** [comment]
> Don't install, it's not safe yet. The last patch was detected

when will it be safe?

**Comment by kittenvr** [comment]
> please make sure you have correctly followed the guide below
> https://github.com/rhunk/SnapEnhance/wiki/Installation-Guide#unrooted

I have
