### ISSUE TITLE
Broken on Android 15 B4

### ISSUE THREAD

**Issue by aayushrautela** [rhunk/SnapEnhance#1170]
### Description

The module is completely broken on Android 15 beta 4.
[snapenhance-logs-1721562034573.zip](https://github.com/user-attachments/files/16324055/snapenhance-logs-1721562034573.zip)

### Reproduction steps

1. Go to Snapchat 
2."SnapEnhance failed to initialize. Please check logs for more details." Error shows up each time

### Logs

```markdown
java.util.NoSuchElementException: Array contains no element matching the predicate.
	at me.rhunk.snapenhance.core.SnapEnhance.initNative(Unknown Source:176)
	at me.rhunk.snapenhance.core.SnapEnhance.init(Unknown Source:26)
	at me.rhunk.snapenhance.core.SnapEnhance.access$init(Unknown Source:0)
	at me.rhunk.snapenhance.core.SnapEnhance$1$3.invokeSuspend(Unknown Source:189)
	at v2.a.resumeWith(Unknown Source:8)
	at U2.s.q(Unknown Source:6)
	at P2.a.resumeWith(Unknown Source:22)
	at v2.a.resumeWith(Unknown Source:31)
	at P2.H.run(Unknown Source:114)
	at P2.S.U(Unknown Source:140)
	at P2.B.x(Unknown Source:104)
	at P2.B.y(Unknown Source:2)
	at me.rhunk.snapenhance.core.SnapEnhance._init_$lambda$4(Unknown Source:60)
	at me.rhunk.snapenhance.core.SnapEnhance.i(Unknown Source:0)
	at me.rhunk.snapenhance.core.d.invoke(Unknown Source:49)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:180)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1353)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1471)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1403)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7464)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2416)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

```

### Snapchat Version

12.87.0.44

### SnapEnhance Version

2.1.0 CI

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
Does LSPosed work yet on A15?

**Comment by aayushrautela** [comment]
I think so, though I have no other modules to check.

**Comment by QstTheDuck** [comment]
I had similar problems when updating to B3 using [this](https://github.com/mywalkb/LSPosed_mod) lsposed module fixed it for me (no idea if this works on B4, currently not home so can't update)

**Comment by aayushrautela** [comment]
I already tried this one, it was not working either.

**Comment by aayushrautela** [comment]
Fixed after using this fork of lsposed.
https://github.com/JingMatrix/LSPosed
Please star the repo to support the dev.
