### ISSUE TITLE
Failed to load Security Features Snapchat may not work properly found in latest debug build of Snapenhance

### ISSUE THREAD

**Issue by IamNickerson** [rhunk/SnapEnhance#1171]
### Description

Getting a popup saying Failed to load Security Features Snapchat may not work properly in latest debug build continuously when starting up Snapchat with Snapenhance with it
![Screenshot_20240722_100423_Snapchat](https://github.com/user-attachments/assets/a9e80779-e581-41bd-bc00-6129bcfc8ff0)

### Reproduction steps

1. Go on `Snapchat modded with latest debug build of snapenhance `
2. Popup appears
3. See a error.

### Logs

```markdown
|V/2024-07-22 09:55:31/core/Feature Better Location initialized in 0 ms
|V/2024-07-22 09:55:31/core/init took 214ms
|V/2024-07-22 09:55:31/core/Feature Better Transcript initialized in 0 ms
|V/2024-07-22 09:55:31/core/libclient lateInit
|V/2024-07-22 09:55:32/core/Activity created: MainActivity
|V/2024-07-22 09:55:32/core/Activity listener a executed in 5 ms
|V/2024-07-22 09:55:32/core/Activity listener h executed in 0 ms
|V/2024-07-22 09:55:32/core/Activity listener j executed in 4 ms
|V/2024-07-22 09:55:32/core/Activity listener A executed in 0 ms
|V/2024-07-22 09:55:32/core/Activity listener h executed in 0 ms
|V/2024-07-22 09:55:32/core/Activity listener v executed in 4 ms
|V/2024-07-22 09:55:32/core/Activity listener h executed in 0 ms
|V/2024-07-22 09:55:32/core/Activity listener l executed in 0 ms
|V/2024-07-22 09:55:32/core/Activity listener h executed in 0 ms
|V/2024-07-22 09:55:32/core/Activity listener h executed in 28 ms
|V/2024-07-22 09:55:32/core/Activity listener l executed in 11 ms
|V/2024-07-22 09:55:32/core/Activity listener d executed in 1 ms
|V/2024-07-22 09:55:32/core/Activity listener h executed in 0 ms
|V/2024-07-22 09:55:32/core/Activity listener l executed in 3 ms
|V/2024-07-22 09:55:32/core/Activity listener b executed in 0 ms
|V/2024-07-22 09:55:32/core/Activity listener d executed in 0 ms
|V/2024-07-22 09:55:32/core/Activity listener i executed in 1 ms
|V/2024-07-22 09:55:32/core/onActivityCreate took 69
|V/2024-07-22 09:55:32/core/Loaded 20 cached messages in 81ms
|V/2024-07-22 09:55:33/core/reloading config
|V/2024-07-22 09:55:33/manager/Syncing remote took 1 ms
|W/2024-07-22 09:55:34/core/Can't load scplugin in safe mode
|I/2024-07-22 09:55:38/FA/App measurement disabled via the manifest
|I/2024-07-22 09:55:38/FA/App measurement initialized, version: 98000
|I/2024-07-22 09:55:38/FA/To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
|I/2024-07-22 09:55:38/FA/To enable faster debug mode event logging run:
  adb shell setprop debug.firebase.analytics.app com.snapchat.android
|V/2024-07-22 09:55:42/LSPatchUpdater/Found embedded SE at /data/user/0/com.snapchat.android/cache/lspatch/me.rhunk.snapenhance/2444198228.apk
|V/2024-07-22 09:55:42/manager/Syncing remote took 0 ms
|V/2024-07-22 09:55:42/LSPatchUpdater/Embedded SE is up to date
|V/2024-07-22 09:55:42/core/reloading config
|E/2024-07-22 09:55:42/core/Failed to load sif
|E/2024-07-22 09:55:42/core/java.lang.IllegalStateException: buffer is empty
	at me.rhunk.snapenhance.core.SnapEnhance.initNative(Unknown Source:128)
	at me.rhunk.snapenhance.core.SnapEnhance.init(SourceFile:11)
	at me.rhunk.snapenhance.core.SnapEnhance.access$init(Unknown Source:0)
	at me.rhunk.snapenhance.core.SnapEnhance$init$3.invokeSuspend(Unknown Source:189)
	at v2.a.resumeWith(Unknown Source:8)
	at U2.s.q(Unknown Source:6)
	at P2.a.resumeWith(Unknown Source:22)
	at v2.a.resumeWith(Unknown Source:31)
	at P2.H.run(Unknown Source:114)
	at P2.S.U(Unknown Source:140)
	at P2.B.x(Unknown Source:104)
	at P2.B.y(Unknown Source:2)
	at me.rhunk.snapenhance.core.SnapEnhance.init(SourceFile:6)
	at me.rhunk.snapenhance.core.XposedLoader.handleLoadPackage$lambda$0(Unknown Source:17)
	at me.rhunk.snapenhance.core.XposedLoader.a(Unknown Source:0)
	at me.rhunk.snapenhance.common.scripting.ui.c.invoke(Unknown Source:214)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1283)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1547)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1484)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7651)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

|V/2024-07-22 09:55:42/core/Feature EndToEndEncryption initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature PreventMessageListAutoScroll initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Scope Sync initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature FriendMutationObserver initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Auto Mark As Read initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature MediaDownloader initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Messaging initialized in 2 ms
|V/2024-07-22 09:55:42/core/Feature StealthMode initialized in 1 ms
|V/2024-07-22 09:55:42/core/Feature Auto Save initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Convert Message Edit initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature UITweaks initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature SnapchatPlus initialized in 1 ms
|V/2024-07-22 09:55:42/core/Feature Prevent message sending initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature DisableMetrics initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature BypassVideoLengthRestriction initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature UnlimitedSnapViewTime initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature AppLock initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature MessageLogger initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Send Override initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature MenuViewInjector initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Meo Passcode Bypass initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Configuration Override initialized in 2 ms
|V/2024-07-22 09:55:42/core/Feature InfiniteStoryBoost initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature PinConversations initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Device Spoofer initialized in 3 ms
|V/2024-07-22 09:55:42/core/Feature ClientBootstrapOverride initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Disable GMS Dialogs initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature NoFriendScoreDelay initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature ProfilePictureDownloader initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature AddFriendSourceSpoof initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Notifications initialized in 4 ms
|V/2024-07-22 09:55:42/core/Feature Camera Tweaks initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Media Upload Quality Override initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature DisableReplayInFF initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Unsaveable Messages initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature FriendFeedMessagePreview initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature HideStreakRestore initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature HideFriendFeedEntry initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature HideQuickAddFriendFeed initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature SnapPreview initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature BypassScreenshotDetection initialized in 1 ms
|V/2024-07-22 09:55:42/core/Feature Half Swipe Notifier initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Disable Confirmation Dialogs initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature MixerStories initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Edit Text Override initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Conversation Toolbox initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Message Indicators initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Prevent Forced Logout initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature SpotlightCommentsUsername initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature StealthModeIndicator initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Disable Permission Requests initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Default Volume Controls initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Disable Memories Snap Feed initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature OperaViewerParamsOverride initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Better Location initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Account Switcher initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Auto Open Snaps initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Media File Picker initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Disable Custom Tabs initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature OldBitmojiSelfie initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Friend Tracker initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Bypass Message Action Restrictions initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature COF Override initialized in 1 ms
|V/2024-07-22 09:55:42/core/Feature Best Friend Pinning initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Call Recorder initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Context Menu Fix initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature ComposerHooks initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Disable Telecom Framework initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Hide Active Music initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature CallStartConfirmation initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature CustomStreaksExpirationFormat initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Custom Theming initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Remove Groups Locked Status initialized in 0 ms
|V/2024-07-22 09:55:42/core/Feature Better Transcript initialized in 0 ms
|V/2024-07-22 09:55:42/core/init took 210ms
|V/2024-07-22 09:55:42/core/libclient lateInit
|V/2024-07-22 09:55:42/core/Activity created: MainActivity
|V/2024-07-22 09:55:42/core/Activity listener a executed in 5 ms
|V/2024-07-22 09:55:42/core/Activity listener j executed in 3 ms
|V/2024-07-22 09:55:42/core/Activity listener h executed in 0 ms
|V/2024-07-22 09:55:42/core/Activity listener h executed in 0 ms
|V/2024-07-22 09:55:42/core/Activity listener A executed in 0 ms
|V/2024-07-22 09:55:42/core/Activity listener h executed in 0 ms
|V/2024-07-22 09:55:42/core/Activity listener l executed in 0 ms
|V/2024-07-22 09:55:42/core/Activity listener v executed in 7 ms
|V/2024-07-22 09:55:42/core/Activity listener h executed in 0 ms
|V/2024-07-22 09:55:42/core/Loaded 20 cached messages in 17ms
|V/2024-07-22 09:55:42/core/Activity listener h executed in 23 ms
|V/2024-07-22 09:55:42/core/Activity listener d executed in 1 ms
|V/2024-07-22 09:55:42/core/Activity listener l executed in 5 ms
|V/2024-07-22 09:55:42/core/Activity listener h executed in 0 ms
|V/2024-07-22 09:55:42/core/Activity listener l executed in 2 ms
|V/2024-07-22 09:55:42/core/Activity listener b executed in 1 ms
|V/2024-07-22 09:55:42/core/Activity listener i executed in 1 ms
|V/2024-07-22 09:55:42/core/Activity listener d executed in 0 ms
|V/2024-07-22 09:55:42/core/onActivityCreate took 56
|V/2024-07-22 09:55:43/core/reloading config
|V/2024-07-22 09:55:43/manager/Syncing remote took 0 ms
|W/2024-07-22 09:55:44/core/Can't load scplugin in safe mode
|I/2024-07-22 09:55:49/FA/App measurement disabled via the manifest
|I/2024-07-22 09:55:49/FA/App measurement initialized, version: 98000
|I/2024-07-22 09:55:49/FA/To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
|I/2024-07-22 09:55:49/FA/To enable faster debug mode event logging run:
  adb shell setprop debug.firebase.analytics.app com.snapchat.android
|V/2024-07-22 09:56:18/core/onConfigChanged
|V/2024-07-22 09:56:18/core/reloading config
|V/2024-07-22 09:56:18/core/onRestartRequired
|V/2024-07-22 09:56:18/core/softRestart
|V/2024-07-22 09:56:19/LSPatchUpdater/Found embedded SE at /data/user/0/com.snapchat.android/cache/lspatch/me.rhunk.snapenhance/2444198228.apk
|V/2024-07-22 09:56:19/manager/Syncing remote took 0 ms
|V/2024-07-22 09:56:19/LSPatchUpdater/Embedded SE is up to date
|V/2024-07-22 09:56:19/core/reloading config
|E/2024-07-22 09:56:19/core/Failed to load sif
|E/2024-07-22 09:56:19/core/java.lang.IllegalStateException: buffer is empty
	at me.rhunk.snapenhance.core.SnapEnhance.initNative(Unknown Source:128)
	at me.rhunk.snapenhance.core.SnapEnhance.init(SourceFile:11)
	at me.rhunk.snapenhance.core.SnapEnhance.access$init(Unknown Source:0)
	at me.rhunk.snapenhance.core.SnapEnhance$init$3.invokeSuspend(Unknown Source:189)
	at v2.a.resumeWith(Unknown Source:8)
	at U2.s.q(Unknown Source:6)
	at P2.a.resumeWith(Unknown Source:22)
	at v2.a.resumeWith(Unknown Source:31)
	at P2.H.run(Unknown Source:114)
	at P2.S.U(Unknown Source:140)
	at P2.B.x(Unknown Source:104)
	at P2.B.y(Unknown Source:2)
	at me.rhunk.snapenhance.core.SnapEnhance.init(SourceFile:6)
	at me.rhunk.snapenhance.core.XposedLoader.handleLoadPackage$lambda$0(Unknown Source:17)
	at me.rhunk.snapenhance.core.XposedLoader.a(Unknown Source:0)
	at me.rhunk.snapenhance.common.scripting.ui.c.invoke(Unknown Source:214)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1283)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1547)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1484)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7651)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Snapchat Version

12.96.0.42

### SnapEnhance Version

2.1.0 (b2bc23d)

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by IamNickerson** [comment]
Alright

**Comment by IamNickerson** [comment]
It's disabled but it's still popping up

**Comment by CatGrls** [comment]
Can someone explain to me how to do this.. I’ve never used GitHub before and I just want to get rid of the Snapchat media thing😭
Discord : e.kltty ( it’s a L )
Instagram : E.grlss ( L )
Pls hellllp this is stressing me out

**Comment by suryadip2008** [comment]
> Can someone explain to me how to do this.. I’ve never used GitHub before and I just want to get rid of the Snapchat media thing😭 Discord : e.kltty ( it’s a L ) Instagram : E.grlss ( L ) Pls hellllp this is stressing me out

Check this out: https://github.com/rhunk/SnapEnhance/issues/1197#issuecomment-2314151624
