### ISSUE TITLE
Failed to ... initialize bridge

### ISSUE THREAD

**Issue by WaffleGodS** [rhunk/SnapEnhance#1181]
### Description

Just updated to Android 15 beta 4, now snap enhanced doesn't work  anyone know how to fix this without resetting my phone back to Android 14?

### Reproduction steps

1. Update to Android 15 beta 4 
2. Open Snapchat 

### Logs

```markdown
"java.util.NoSuchElementException: Array contains no element matching the predicate.
	at me.rhunk.snapenhance.core.SnapEnhance.initNative(Unknown Source:176)
	at me.rhunk.snapenhance.core.SnapEnhance.init(Unknown Source:26)
	at me.rhunk.snapenhance.core.SnapEnhance.access$init(Unknown Source:0)
	at me.rhunk.snapenhance.core.SnapEnhance$1$3.invokeSuspend(Unknown Source:189)
	at v2.a.resumeWith(Unknown Source:8)
	at U2.s.q(Unknown Source:6)
	at P2.a.resumeWith(Unknown Source:22)
	at v2.a.resumeWith(Unknown Source:31)
	at P2.H.run(Unknown Source:114)
	at P2.S.U(Unknown Source:140)
	at P2.B.x(Unknown Source:104)
	at P2.B.y(Unknown Source:2)
	at me.rhunk.snapenhance.core.SnapEnhance._init_$lambda$4(Unknown Source:60)
	at me.rhunk.snapenhance.core.SnapEnhance.i(Unknown Source:0)
	at me.rhunk.snapenhance.core.d.invoke(Unknown Source:49)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at wGXP.Z.gh.RsLR.G.KU.Wg.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:180)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1353)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1471)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1403)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7464)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2416)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
"
```

### Snapchat Version

version 13.0.0.50 com.snapchat.android

### SnapEnhance Version

2.1.0

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by suryadip2008** [comment]
@WaffleGodS Try this version of Lsposed and see if it works:
https://github.com/JingMatrix/LSPosed/releases/tag/v1.10.0

This is a fork which adds supports for Android 15 Beta 4.

**Comment by bocajthomas** [comment]
> @WaffleGodS Try this version of Lsposed and see if it works: https://github.com/JingMatrix/LSPosed/releases/tag/v1.10.0
> 
> This is a fork which adds supports for Android 15 Beta 4.

I think we all might have to move to Forked versions of LSPosed / LSPatch
