### ISSUE TITLE
Failed To Initialize Bridge

### ISSUE THREAD

**Issue by ArtificiallyThrown** [rhunk/SnapEnhance#1213]
### Description

Been using Snapenhance for months, started using the version with the "Media Uploaded" fix, after about a week the bridge for snap enhance fails, it even fails on older versions that I used for months.
I have found that I can use old versions that allow me to disable "Native Hooks" (and then anything that doesn't use those hooks works) but since they seem to be on by default in newer versions it just doesn't work. 

I have no idea what happened, it was working one day, and then the next day it stopped working entirely, like i said even for versions I've been using for months. 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs

```markdown
(this is the error snapenhance gives me)

java.util.NoSuchElementException: Array contains no element matching the predicate.
at me.rhunk.snapenhance.core.SnapEnhance.initNative(Unknown Source:401)
at me.rhunk.snapenhance.core.SnapEnhance.init(SourceFile:11)
at me.rhunk.snapenhance.core.SnapEnhance.access$init(Unknown Source:0)
at me.rhunk.snapenhance.core.SnapEnhance$init$3.invokeSuspend(Unknown Source:189)
at v2.a.resumeWith(Unknown Source:8)
at U2.s.q(Unknown Source:6)
at P2.a.resumeWith(Unknown Source:22)
at v2.a.resumeWith(Unknown Source:31)
at U2.s.q(Unknown Source:6)
at P2.a.resumeWith(Unknown Source:22)
at v2.a.resumeWith(Unknown Source:31)
at P2.H.run(Unknown Source:114)
at P2.S.U(Unknown Source:140)
at P2.B.x(Unknown Source:104)
at P2.B.y(Unknown Source:2)
at me.rhunk.snapenhance.core.SnapEnhance.init(SourceFile:6)
at me.rhunk.snapenhance.core.XposedLoader.handleLoadPackage$lambda$0(Unknown Source:17)
at me.rhunk.snapenhance.core.XposedLoader.a(Unknown Source:0)
at me.rhunk.snapenhance.common.messaging.a.invoke(Unknown Source:200)
at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
at yOBU.uWzLD.qSjev.sQCdK.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
at J.callback(Unknown Source:180)
at LSPHooker_.attach(Unknown Source:11)
at android.app.Instrumentation.newApplication(Instrumentation.java:1353)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7359)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8592)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

### Snapchat Version

12.46.0.51

### SnapEnhance Version

All Latest Versions (Debug CL)

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by Seanzuwu** [comment]
This IS the version of LSPosed that I use unfortunately, I wonder what could have changed :(

**Comment by ArtificiallyThrown** [comment]
I'm on a rooted Pixel 8 Pro. 

I was literally using Snapenhance, went to bed, woke up the next day getting that error, that's why I'm so confused as nothing changed from what I can tell.

**Comment by Seanzuwu** [comment]
> @Seanzuwu what version of Android are you on? which device?

I'm on a rooted Pixel 8 Pro - Android 14

I was literally using Snapenhance, went to bed, woke up the next day getting that error, that's why I'm so confused as nothing changed from what I can tell.

**Comment by Seanzuwu** [comment]
Holy! 

Whatever you did fixed it!

**Comment by Seanzuwu** [comment]
will this work continue to persist in future versions? Thanks!
