### ISSUE TITLE
Snapchat keeps crashing on all mi poco devices after new update

### ISSUE THREAD

**Issue by LukyBrat** [rhunk/SnapEnhance#1265]
### Description

When u download the newest HyperOS you wont open snapchat with snapenhance only the official snapchat
ill send the logs down below

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs

```markdown
java.lang.RuntimeException: Unable to instantiate application com.snap.mushroom.app.MushroomApplication package com.snapchat.android:
java.lang.ClassNotFoundException: Didn't find class
"com.snap.mushroom.app.MushroomApplication" on path: DexPathList[[zip file "/data/app/ ~~593gC1XEjmSAhpsll-alAw==/com.snapc hat.android-le9NVZLP8pDiZkEGynsgHA==/
base.apk"],nativeLibraryDirectories=[/data/app/
~~593gC1XEjmSAhpsll-alAw==/com.snapchat.and roid-le9NVZLP8pDiZkEGynsgHA==/lib/arm64, /data/ app/~~593gC1XEjmSAhpsll-alAw==/com.snapchat .android-le9NVZLP8pDiZkEGynsgHA==/base.apk!/ lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at
android.app.LoadedApk.makeApplicationInner(Load
edApk.java:1495)
at
android.app.LoadedApk.makeApplicationInner(Load
edApk.java:1424)
at
android.app.ActivityThread.handleBindApplication (A
ctivityThread.java:7479)
at android.app.ActivityThread.-$ $Nest$mhandleBindApplication (Unknown Source:0)
at
android.app.ActivityThread$H.handleMessage(Activi
tyThread.java:2382)
at
android.os.Handler.dispatchMessage(Handler.java:1
06)
at android.os.Looper.loopOnce (Looper.java:224) at android.os.Looper.loop(Looper.java:318)
at
android.app.ActivityThread.main(ActivityThread.java:
8790)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArg
sCaller.run(RuntimeInit.java:561)android.app.ActivityThread.main(ActivityThread.java:
8790)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArg
sCaller.run(RuntimeInit.java:561)
at
com.android.internal.os.ZygoteInit.main(ZygoteInit.ja
va:1013)
Caused by: java.lang.ClassNotFoundException: Didn't find class
"com.snap.mushroom.app.MushroomApplication" on path: DexPathList[[zip file "/data/app/ ~~593gC1XEjmSAhpsll-alAw==/com.snapch at.android-le9NVZLP8pDiZkEGynsgHA==/ base.apk"],nativeLibraryDirectories=[/data/app/ ~~593gC1XEjmSAhpsll-alAw==/com.snapchat.andr oid-le9NVZLP8pDiZkEGynsgHA==/lib/arm64, /data/ app/~~593gC1XEjmSAhpsll-alAw==/com.snapcha t.android-le9NVZLP8pDiZkEGynsgHA==/base.apk!/ lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at
dalvik.system.BaseDexClassLoader.findClass(BaseD
exClassLoader.java:259)
at
java.lang.ClassLoader.loadClass(ClassLoader.java:63
7)
at
java.lang.ClassLoader.loadClass(ClassLoader.java:57
3)
at
android.app.AppComponentFactory.instantiateApplic ation (AppComponentFactory.java:76)
at
android.app.Instrumentation.newApplication (Instru
mentation.java:1289)
at
android.app.LoadedApk.makeApplicationInner(Load
edApk.java:1487)
11 more
```

### Snapchat Version

all of them

### SnapEnhance Version

all of them

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [ ] This issue is not a duplicate.

**Comment by ritik0071** [comment]
Use older version or otherwise uh will face crash and even your account gonna be ban

**Comment by ritik0071** [comment]
> > Use older version or otherwise uh will face crash and even your account gonna be ban
>  
> If u mean Os older version ik but i dont want to root my phone cuz of that 

Bro my device is non rooted

**Comment by LukyBrat** [comment]
> > > Use older version or otherwise uh will face crash and even your account gonna be ban
> > 
> > 
> > If u mean Os older version ik but i dont want to root my phone cuz of that
> 
> Bro my device is non rooted

how do i get the older version?

**Comment by ritik0071** [comment]
Connect with me on telegram @Tva420

**Comment by ZmaZes** [comment]
I'm also experiencing this issue on OneUI 6.1.1.
Never updated Snapchat or SnapEnhance but I did update my phone. I don't use Snapchat super often so I only noticed it was broken when I got a notification saying that the app kept crashing, and then wouldn't open.

**Comment by slc9x** [comment]
Same I tried every version of snapchat and snapenhance and ever way always crashes on the start of the app I am on android 14 on ui 6.1

**Comment by ZmaZes** [comment]
This is definitely a problem with OneUI 6.1 because another app I modified with LSPatch is having the exact same issue. Makes me wonder if Samsung is trying to prevent app patching or something. Not sure what to do.

**Comment by slc9x** [comment]
Yah bro I am having same issues with other apps not only snapenhance fuck the os update I am hating where Android is going since the block of access for the app data storge I think root is the next go

**Comment by ZmaZes** [comment]
It is quite dissapointing.
I made a Reddit post to see if anyone else has found a fix for it. You're welcome to follow/like/comment or whatever, I have no idea what the actual issue is or how to get around it. If I had to guess it's something to do with signatures and maybe you can use different ones somehow, not sure. Hoping some other smart person has figured out a workaround.
https://www.reddit.com/r/oneui/s/WKMh5hknSx

**Comment by suryadip2008** [comment]
> It is quite dissapointing. I made a Reddit post to see if anyone else has found a fix for it. You're welcome to follow/like/comment or whatever, I have no idea what the actual issue is or how to get around it. If I had to guess it's something to do with signatures and maybe you can use different ones somehow, not sure. Hoping some other smart person has figured out a workaround. https://www.reddit.com/r/oneui/s/WKMh5hknSx

I posted the same in Reddit, I will post it again here too but now the solution will be for both rooted and non rooted devices.
**This solution should work.**

_**Non rooted devices:**_
Follow each and every step in order to fix this issue:

First uninstall the existing Lspatch and any installed patch apps(if installed).

1. Go to this link: [Link](https://nightly.link/JingMatrix/LSPatch/actions/runs/10888848425)

2. Download the debug zip from that link. (Remember to download that debug one only and not the release one)

3. Extract the zip file you have just downloaded.

4. Install the manager apk and then patch apps with the Lspatch that you have just installed.

**_Rooted devices:_**

First uninstall the existing Lsposed.

1. Go to this link: [Link](https://nightly.link/JingMatrix/LSPosed/actions/runs/11156481437)

2. Download the debug zip from that link. (Remember to download that debug one only and not the release one)

3. Flash the zip file in Magisk and then reboot your phone.

4. Then start using the new Lsposed with SE.

**Comment by ZmaZes** [comment]
Thanks for your help, that fixed the issue, although now Snapchat won't let me login from my phone so we'll have to wait a bit and see if that goes away. I tried looking around for LSPatch updates but I wasn't having much luck so I definitely appreciate the help.

**Comment by DToothedTed** [comment]
> > It is quite dissapointing. I made a Reddit post to see if anyone else has found a fix for it. You're welcome to follow/like/comment or whatever, I have no idea what the actual issue is or how to get around it. If I had to guess it's something to do with signatures and maybe you can use different ones somehow, not sure. Hoping some other smart person has figured out a workaround. https://www.reddit.com/r/oneui/s/WKMh5hknSx
> 
> I posted the same in Reddit, I will post it again here too but now the solution will be for both rooted and non rooted devices. **This solution should work.**
> 
> _**Non rooted devices:**_ Follow each and every step in order to fix this issue:
> 
> First uninstall the existing Lspatch and any installed patch apps(if installed).
> 
>     1. Go to this link: [Link](https://nightly.link/JingMatrix/LSPatch/actions/runs/10888848425)
> 
>     2. Download the debug zip from that link. (Remember to download that debug one only and not the release one)
> 
>     3. Extract the zip file you have just downloaded.
> 
>     4. Install the manager apk and then patch apps with the Lspatch that you have just installed.
> 
> 
> **_Rooted devices:_**
> 
> First uninstall the existing Lsposed.
> 
>     1. Go to this link: [Link](https://nightly.link/JingMatrix/LSPosed/actions/runs/11156481437)
> 
>     2. Download the debug zip from that link. (Remember to download that debug one only and not the release one)
> 
>     3. Flash the zip file in Magisk and then reboot your phone.
> 
>     4. Then start using the new Lsposed with SE.

Link expired, can you please update?
