### ISSUE TITLE
Crashing on profile, SnapchatPlus and Beter location not working

### ISSUE THREAD

**Issue by LolekLiam** [rhunk/SnapEnhance#1276]
### Description

When i click on a profile(my or my friend's, even clicking on a friend on the snapmap), Snapchat crashes. Better location and Snapchat Plus also fail to load. The settings gear is also missing, but the entire top section can be tapped for showing snapenhance.
[snapenhance-logs-1728056269467.zip](https://github.com/user-attachments/files/17260947/snapenhance-logs-1728056269467.zip)

### Reproduction steps

1. Open Snapchat
2. Immediately see failed to init feature SnapchatPlus and Better location 
3. No settings gear
4. Try to click on a profile
5. Crash

### Logs

```markdown
java.lang.IndexOutOfBoundsException: index=0 out of bounds (limit=0, nb=4)
	at java.nio.Buffer.checkIndex(Buffer.java:764)
	at java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:601)
	at android.graphics.fonts.FontFileUtil.analyzeStyle(FontFileUtil.java:96)
	at android.graphics.fonts.Font$Builder.build(Font.java:451)
	at android.graphics.Typeface$Builder.build(Typeface.java:751)
	at android.content.res.ResourcesImpl.loadFont(ResourcesImpl.java:1051)
	at android.content.res.Resources.getFont(Resources.java:506)
	at me.rhunk.snapenhance.core.ui.UserInterface.init$lambda$4(Unknown Source:51)
	at me.rhunk.snapenhance.core.ui.UserInterface.a(Unknown Source:0)
	at f3.l.invoke(Unknown Source:22)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$2.afterHookedMethod(Unknown Source:12)
	at SYt.skxZyG.jN.EyopghgD.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.getValue(Unknown Source:25)
	at u9f.d(SourceFile:13)
	at u9f.c(SourceFile:1)
	at UAj.a(SourceFile:1)
	at UAj.c(SourceFile:1)
	at Eq7.d(SourceFile:19)
	at Gcd.run(SourceFile:119)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Snapchat Version

12.45.0.55

### SnapEnhance Version

2.1.0 c695145

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by LolekLiam** [comment]
screen recording:
https://github.com/user-attachments/assets/00198775-072b-4f98-8589-b213364d6e36

**Comment by LolekLiam** [comment]
disabling snapchat plus and better location doesn't help, i still get a crash upon clicking on a profile and settings gear still isnt visible.

**Comment by LolekLiam** [comment]
i am using lsposed-mod and rooted magisk v27.0(latest right now). Android 14, Xiaomi Redmi 12 5G, Snapdragon 4 gen 2 processor. hope this info helps

**Comment by LolekLiam** [comment]
ok, just figured it out why this stuff is happening: native hooks are causing something with fonts, so it causes crashing, snapchat plus wasnt working because unreleased snapchat plus feature isnt supported for this version of snapchat, and better location is probably not working because battery percentage isnt supported in this version(maybe, idk), i want to think that because the logs seem to say that it cannot find that method/function to call.
