### ISSUE TITLE
Holding on a friend crashes snapchat 

### ISSUE THREAD

**Issue by BrokenOG** [rhunk/SnapEnhance#1309]
### Description

When we hold a friend in friend feed to get the options (manage friendship, notification setting etc) snapchat crashes instantly 

### Reproduction steps

 1. Open chat
 2. Open friend feed
 3. Hold on a friend (any)
 4. Snapchat crashes 

### Logs

```markdown
|V/2024-12-10 20:39:32/core/reloading config
|V/2024-12-10 20:39:32/manager/Syncing remote took 133 ms
|V/2024-12-10 20:39:32/core/reloading config
|V/2024-12-10 20:39:33/manager/Syncing remote took 109 ms
|E/2024-12-10 20:39:34/core/Snapchat crash
|E/2024-12-10 20:39:34/core/java.lang.IllegalStateException: Could not load font
	at B0.n.a(Unknown Source:100)
	at B0.n.b(Unknown Source:24)
	at D0.c.<init>(Unknown Source:375)
	at B.e.d(Unknown Source:37)
	at B.e.b(Unknown Source:0)
	at B.k.b(Unknown Source:214)
	at androidx.compose.ui.node.y.b(Unknown Source:10)
	at f0.H.b(Unknown Source:0)
	at androidx.compose.ui.node.y.b(Unknown Source:10)
	at A.L.invoke(Unknown Source:111)
	at X.u.d(Unknown Source:59)
	at X.x.a(Unknown Source:47)
	at X.y.c(Unknown Source:153)
	at androidx.compose.ui.node.W.e(Unknown Source:4)
	at androidx.compose.ui.node.K.D0(Unknown Source:133)
	at androidx.compose.ui.node.K.b(Unknown Source:110)
	at s.X.b(Unknown Source:593)
	at s.W.measure-3p2s80s(Unknown Source:44)
	at androidx.compose.ui.node.t.b(Unknown Source:38)
	at s.Q.b(Unknown Source:32)
	at androidx.compose.ui.node.y.b(Unknown Source:10)
	at s.c0.b(Unknown Source:116)
	at androidx.compose.ui.node.y.b(Unknown Source:10)
	at s.y.b(Unknown Source:98)
	at androidx.compose.ui.node.y.b(Unknown Source:10)
	at A.L.invoke(Unknown Source:111)
	at X.u.d(Unknown Source:59)
	at X.x.a(Unknown Source:47)
	at X.y.c(Unknown Source:153)
	at androidx.compose.ui.node.W.e(Unknown Source:4)
	at androidx.compose.ui.node.K.D0(Unknown Source:133)
	at androidx.compose.ui.node.K.b(Unknown Source:110)
	at s.p.measure-3p2s80s(Unknown Source:82)
	at androidx.compose.ui.node.t.b(Unknown Source:38)
	at f0.H.b(Unknown Source:0)
	at androidx.compose.ui.node.y.b(Unknown Source:10)
	at f0.H.b(Unknown Source:0)
	at androidx.compose.ui.node.y.b(Unknown Source:10)
	at A.L.invoke(Unknown Source:111)
	at X.u.d(Unknown Source:59)
	at X.x.a(Unknown Source:47)
	at X.y.c(Unknown Source:153)
	at androidx.compose.ui.node.W.e(Unknown Source:4)
	at androidx.compose.ui.node.K.D0(Unknown Source:133)
	at androidx.compose.ui.node.K.b(Unknown Source:110)
	at s.X.b(Unknown Source:115)
	at s.W.measure-3p2s80s(Unknown Source:44)
	at androidx.compose.ui.node.t.b(Unknown Source:38)
	at s.y.b(Unknown Source:98)
	at androidx.compose.ui.node.y.b(Unknown Source:10)
	at A.L.invoke(Unknown Source:111)
	at X.u.d(Unknown Source:59)
	at X.x.a(Unknown Source:47)
	at X.y.c(Unknown Source:153)
	at androidx.compose.ui.node.W.e(Unknown Source:4)
	at androidx.compose.ui.node.K.D0(Unknown Source:133)
	at androidx.compose.ui.node.K.b(Unknown Source:110)
	at androidx.compose.ui.layout.T.measure-3p2s80s(Unknown Source:38)
	at androidx.compose.ui.node.t.b(Unknown Source:38)
	at A.L.invoke(Unknown Source:111)
	at X.u.d(Unknown Source:59)
	at X.x.a(Unknown Source:47)
	at X.y.c(Unknown Source:153)
	at androidx.compose.ui.node.W.e(Unknown Source:4)
	at androidx.compose.ui.node.K.D0(Unknown Source:133)
	at androidx.compose.ui.node.D.I(Unknown Source:17)
	at androidx.compose.ui.node.S.d(Unknown Source:2)
	at androidx.compose.ui.node.S.n(Unknown Source:17)
	at androidx.compose.ui.node.S.k(Unknown Source:62)
	at androidx.compose.ui.platform.t.onMeasure(Unknown Source:80)
	at android.view.View.measure(View.java:27653)
	at androidx.compose.ui.platform.a.internalOnMeasure$ui_release(Unknown Source:63)
	at androidx.compose.ui.platform.a.onMeasure(Unknown Source:3)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1613)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:883)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
	at androidx.cardview.widget.CardView.onMeasure(Unknown Source:0)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1613)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:883)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
	at android.view.View.measure(View.java:27653)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1592)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
	at android.widget.ScrollView.onMeasure(ScrollView.java:552)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
	at EG4.b(SourceFile:1)
	at CG4.invoke(SourceFile:1)
	at I6a.a(SourceFile:48)
	at NK3.r0(SourceFile:1)
	at EG4.onMeasure(SourceFile:18)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
	at com.snapchat.deck.views.DeckView.b(SourceFile:1)
	at OG4.run(SourceFile:1)
	at eOh.c(SourceFile:5)
	at com.snapchat.deck.views.DeckView.onMeasure(Unknown Source:7)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1613)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:883)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
	at com.android.internal.policy.DecorView.measureChildWithMargins(DecorView.java:3254)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:948)
	at android.view.View.measure(View.java:27653)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4713)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3127)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3521)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2811)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10277)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1760)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1769)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1273)
	at android.view.Choreographer.doFrame(Choreographer.java:1140)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1743)
	at android.os.Handler.handleCallback(Handler.java:1013)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9221)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
Caused by: java.lang.IllegalStateException: Unable to load font ResourceFont(resId=500, weight=FontWeight(weight=500), style=Normal, loadingStrategy=Blocking)
	at A.r.invoke(Unknown Source:1945)
	at B0.n.a(Unknown Source:53)
	... 143 more
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x1f4
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:440)
	at android.content.res.Resources.getValue(Resources.java:1544)
	at R0.n.a(Unknown Source:5)
	at T3.d.j(Unknown Source:17)
	at B0.b.c(Unknown Source:16)
	at A.r.invoke(Unknown Source:1881)
	... 144 more

|V/2024-12-10 20:39:41/manager/Loading RemoteSideContext
|V/2024-12-10 20:39:41/manager/Syncing remote took 29 ms
|V/2024-12-10 20:39:41/LSPatchUpdater/Found embedded SE at /data/user/0/com.snapchat.android/cache/lspatch/me.rhunk.snapenhance/3027962436.apk
|V/2024-12-10 20:39:41/LSPatchUpdater/Embedded SE is up to date
|V/2024-12-10 20:39:41/core/reloading config
|V/2024-12-10 20:39:41/core/old signature cache [["A8 03 1F F8 C2 00 00 94",[3064024]],["00 E4 00 6F 29 00 80 52 76 00 04 8B",[5953176]],["FF FF 00 A9 3F 00 00 F9",[22767004]]]
|W/2024-12-10 20:39:41/core/sif is disabled
|V/2024-12-10 20:39:41/core/init took 315ms
|V/2024-12-10 20:39:41/core/libclient lateInit
|V/2024-12-10 20:39:42/core/Activity created: MainActivity
|V/2024-12-10 20:39:42/core/onActivityCreate took 63
|V/2024-12-10 20:39:42/core/reloading config
|V/2024-12-10 20:39:42/manager/Syncing remote took 71 ms
|V/2024-12-10 20:39:42/core/Loaded 20 cached messages in 473ms
|I/2024-12-10 20:39:42/manager/sif is up to date (compat_test-0.0.2)
|I/2024-12-10 20:39:44/FA/App measurement disabled via the manifest
|I/2024-12-10 20:39:44/FA/App measurement initialized, version: 110008
|I/2024-12-10 20:39:44/FA/To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
|I/2024-12-10 20:39:44/FA/To enable faster debug mode event logging run:
  adb shell setprop debug.firebase.analytics.app com.snapchat.android
|E/2024-12-10 20:39:48/core/Snapchat crash
|D/2024-12-10 20:40:09/manager/Saving logs, this may take a while ...
```

### Snapchat Version

V12.81 

### SnapEnhance Version

Latest CI 

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by TheFloyds4240** [comment]
I'm having this same issue. Saw in another thread that disabling Android Action Menu V2 in the COF Experiments fixes this, but that didn't work for me.

**Comment by BrokenOG** [comment]
> I'm having this same issue. Saw in another thread that disabling Android Action Menu V2 in the COF Experiments fixes this, but that didn't work for me.

Doesn't work for me too tried with both action menu v2 enabled nd disabled same result

**Comment by Fraitali** [comment]
Help

**Comment by NMBlanco** [comment]
Same issue here on 12.80

**Comment by Quasar-IO** [comment]
> ### Description
> When we hold a friend in friend feed to get the options (manage friendship, notification setting etc) snapchat crashes instantly
> 
> ### Reproduction steps
> 1. Open chat
> 2. Open friend feed
> 3. Hold on a friend (any)
> 4. Snapchat crashes
> 
> ### Logs
> ```
> |V/2024-12-10 20:39:32/core/reloading config
> |V/2024-12-10 20:39:32/manager/Syncing remote took 133 ms
> |V/2024-12-10 20:39:32/core/reloading config
> |V/2024-12-10 20:39:33/manager/Syncing remote took 109 ms
> |E/2024-12-10 20:39:34/core/Snapchat crash
> |E/2024-12-10 20:39:34/core/java.lang.IllegalStateException: Could not load font
> 	at B0.n.a(Unknown Source:100)
> 	at B0.n.b(Unknown Source:24)
> 	at D0.c.<init>(Unknown Source:375)
> 	at B.e.d(Unknown Source:37)
> 	at B.e.b(Unknown Source:0)
> 	at B.k.b(Unknown Source:214)
> 	at androidx.compose.ui.node.y.b(Unknown Source:10)
> 	at f0.H.b(Unknown Source:0)
> 	at androidx.compose.ui.node.y.b(Unknown Source:10)
> 	at A.L.invoke(Unknown Source:111)
> 	at X.u.d(Unknown Source:59)
> 	at X.x.a(Unknown Source:47)
> 	at X.y.c(Unknown Source:153)
> 	at androidx.compose.ui.node.W.e(Unknown Source:4)
> 	at androidx.compose.ui.node.K.D0(Unknown Source:133)
> 	at androidx.compose.ui.node.K.b(Unknown Source:110)
> 	at s.X.b(Unknown Source:593)
> 	at s.W.measure-3p2s80s(Unknown Source:44)
> 	at androidx.compose.ui.node.t.b(Unknown Source:38)
> 	at s.Q.b(Unknown Source:32)
> 	at androidx.compose.ui.node.y.b(Unknown Source:10)
> 	at s.c0.b(Unknown Source:116)
> 	at androidx.compose.ui.node.y.b(Unknown Source:10)
> 	at s.y.b(Unknown Source:98)
> 	at androidx.compose.ui.node.y.b(Unknown Source:10)
> 	at A.L.invoke(Unknown Source:111)
> 	at X.u.d(Unknown Source:59)
> 	at X.x.a(Unknown Source:47)
> 	at X.y.c(Unknown Source:153)
> 	at androidx.compose.ui.node.W.e(Unknown Source:4)
> 	at androidx.compose.ui.node.K.D0(Unknown Source:133)
> 	at androidx.compose.ui.node.K.b(Unknown Source:110)
> 	at s.p.measure-3p2s80s(Unknown Source:82)
> 	at androidx.compose.ui.node.t.b(Unknown Source:38)
> 	at f0.H.b(Unknown Source:0)
> 	at androidx.compose.ui.node.y.b(Unknown Source:10)
> 	at f0.H.b(Unknown Source:0)
> 	at androidx.compose.ui.node.y.b(Unknown Source:10)
> 	at A.L.invoke(Unknown Source:111)
> 	at X.u.d(Unknown Source:59)
> 	at X.x.a(Unknown Source:47)
> 	at X.y.c(Unknown Source:153)
> 	at androidx.compose.ui.node.W.e(Unknown Source:4)
> 	at androidx.compose.ui.node.K.D0(Unknown Source:133)
> 	at androidx.compose.ui.node.K.b(Unknown Source:110)
> 	at s.X.b(Unknown Source:115)
> 	at s.W.measure-3p2s80s(Unknown Source:44)
> 	at androidx.compose.ui.node.t.b(Unknown Source:38)
> 	at s.y.b(Unknown Source:98)
> 	at androidx.compose.ui.node.y.b(Unknown Source:10)
> 	at A.L.invoke(Unknown Source:111)
> 	at X.u.d(Unknown Source:59)
> 	at X.x.a(Unknown Source:47)
> 	at X.y.c(Unknown Source:153)
> 	at androidx.compose.ui.node.W.e(Unknown Source:4)
> 	at androidx.compose.ui.node.K.D0(Unknown Source:133)
> 	at androidx.compose.ui.node.K.b(Unknown Source:110)
> 	at androidx.compose.ui.layout.T.measure-3p2s80s(Unknown Source:38)
> 	at androidx.compose.ui.node.t.b(Unknown Source:38)
> 	at A.L.invoke(Unknown Source:111)
> 	at X.u.d(Unknown Source:59)
> 	at X.x.a(Unknown Source:47)
> 	at X.y.c(Unknown Source:153)
> 	at androidx.compose.ui.node.W.e(Unknown Source:4)
> 	at androidx.compose.ui.node.K.D0(Unknown Source:133)
> 	at androidx.compose.ui.node.D.I(Unknown Source:17)
> 	at androidx.compose.ui.node.S.d(Unknown Source:2)
> 	at androidx.compose.ui.node.S.n(Unknown Source:17)
> 	at androidx.compose.ui.node.S.k(Unknown Source:62)
> 	at androidx.compose.ui.platform.t.onMeasure(Unknown Source:80)
> 	at android.view.View.measure(View.java:27653)
> 	at androidx.compose.ui.platform.a.internalOnMeasure$ui_release(Unknown Source:63)
> 	at androidx.compose.ui.platform.a.onMeasure(Unknown Source:3)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
> 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1613)
> 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:883)
> 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
> 	at androidx.cardview.widget.CardView.onMeasure(Unknown Source:0)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
> 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1613)
> 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:883)
> 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
> 	at android.view.View.measure(View.java:27653)
> 	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1592)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
> 	at android.widget.ScrollView.onMeasure(ScrollView.java:552)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
> 	at EG4.b(SourceFile:1)
> 	at CG4.invoke(SourceFile:1)
> 	at I6a.a(SourceFile:48)
> 	at NK3.r0(SourceFile:1)
> 	at EG4.onMeasure(SourceFile:18)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
> 	at com.snapchat.deck.views.DeckView.b(SourceFile:1)
> 	at OG4.run(SourceFile:1)
> 	at eOh.c(SourceFile:5)
> 	at com.snapchat.deck.views.DeckView.onMeasure(Unknown Source:7)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
> 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1613)
> 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:883)
> 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7107)
> 	at com.android.internal.policy.DecorView.measureChildWithMargins(DecorView.java:3254)
> 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:205)
> 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:948)
> 	at android.view.View.measure(View.java:27653)
> 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4713)
> 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3127)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3521)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2811)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10277)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1760)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1769)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:1273)
> 	at android.view.Choreographer.doFrame(Choreographer.java:1140)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1743)
> 	at android.os.Handler.handleCallback(Handler.java:1013)
> 	at android.os.Handler.dispatchMessage(Handler.java:101)
> 	at android.os.Looper.loopOnce(Looper.java:226)
> 	at android.os.Looper.loop(Looper.java:328)
> 	at android.app.ActivityThread.main(ActivityThread.java:9221)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
> Caused by: java.lang.IllegalStateException: Unable to load font ResourceFont(resId=500, weight=FontWeight(weight=500), style=Normal, loadingStrategy=Blocking)
> 	at A.r.invoke(Unknown Source:1945)
> 	at B0.n.a(Unknown Source:53)
> 	... 143 more
> Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x1f4
> 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:440)
> 	at android.content.res.Resources.getValue(Resources.java:1544)
> 	at R0.n.a(Unknown Source:5)
> 	at T3.d.j(Unknown Source:17)
> 	at B0.b.c(Unknown Source:16)
> 	at A.r.invoke(Unknown Source:1881)
> 	... 144 more
> 
> |V/2024-12-10 20:39:41/manager/Loading RemoteSideContext
> |V/2024-12-10 20:39:41/manager/Syncing remote took 29 ms
> |V/2024-12-10 20:39:41/LSPatchUpdater/Found embedded SE at /data/user/0/com.snapchat.android/cache/lspatch/me.rhunk.snapenhance/3027962436.apk
> |V/2024-12-10 20:39:41/LSPatchUpdater/Embedded SE is up to date
> |V/2024-12-10 20:39:41/core/reloading config
> |V/2024-12-10 20:39:41/core/old signature cache [["A8 03 1F F8 C2 00 00 94",[3064024]],["00 E4 00 6F 29 00 80 52 76 00 04 8B",[5953176]],["FF FF 00 A9 3F 00 00 F9",[22767004]]]
> |W/2024-12-10 20:39:41/core/sif is disabled
> |V/2024-12-10 20:39:41/core/init took 315ms
> |V/2024-12-10 20:39:41/core/libclient lateInit
> |V/2024-12-10 20:39:42/core/Activity created: MainActivity
> |V/2024-12-10 20:39:42/core/onActivityCreate took 63
> |V/2024-12-10 20:39:42/core/reloading config
> |V/2024-12-10 20:39:42/manager/Syncing remote took 71 ms
> |V/2024-12-10 20:39:42/core/Loaded 20 cached messages in 473ms
> |I/2024-12-10 20:39:42/manager/sif is up to date (compat_test-0.0.2)
> |I/2024-12-10 20:39:44/FA/App measurement disabled via the manifest
> |I/2024-12-10 20:39:44/FA/App measurement initialized, version: 110008
> |I/2024-12-10 20:39:44/FA/To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
> |I/2024-12-10 20:39:44/FA/To enable faster debug mode event logging run:
>   adb shell setprop debug.firebase.analytics.app com.snapchat.android
> |E/2024-12-10 20:39:48/core/Snapchat crash
> |D/2024-12-10 20:40:09/manager/Saving logs, this may take a while ...
> ```
> 
> ### Snapchat Version
> V12.81
> 
> ### SnapEnhance Version
> Latest CI
> 
> ### Agreement
> * [x]  This is not a bug regarding Snapchat+.
> * [x]  I have provided a detailed description of the issue.
> * [x]  I have attached a log if deemed necessary.
> * [x]  This issue is not a duplicate.

Use an earlier build of SnapEnhance. It's a Friend Feed font import issue of all things. Using an earlier SE build fixes (reverses) this.
