### ISSUE TITLE
Wrong arch of SnapEnhance leads to UnsatisfiedLinkError when starting Snapchat 

### ISSUE THREAD

**Issue by Flole998** [rhunk/SnapEnhance#1312]
### Description

I am trying to run SnapEnhance armv7 debug on LineageOS 18.1 and Snapchat can not be opened as an error message from SnapEnhance appears.

### Reproduction steps

1. Start Snapchat

### Logs

```markdown
java.lang.UnsatisfiedLinkError: LspModuleClassLoader[module=/data/app/~~qtedy2uyGaXwTff7Quok7Q==/me.rhunk.snapenhance-cRjPuBlWxZ4zOJ2ft1hv4Q==/base.apk, m0[DexPathList[[dex file "InMemoryDexFile[cookie=[0, 531309662320, 531309667024]]"],nativeLibraryDirectories=[/data/app/~~qtedy2uyGaXwTff7Quok7Q==/me.rhunk.snapenhance-cRjPuBlWxZ4zOJ2ft1hv4Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /system/product/lib64, /system/vendor/lib64]]]] couldn't find "lib771b305dd25c89cb.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1083)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
	at java.lang.System.loadLibrary(System.java:1664)
	at me.rhunk.snapenhance.nativelib.NativeLib.initOnce(Unknown Source:11)
	at me.rhunk.snapenhance.core.SnapEnhance.initNative(Unknown Source:114)
	at me.rhunk.snapenhance.core.SnapEnhance.init(SourceFile:11)
	at me.rhunk.snapenhance.core.SnapEnhance.access$init(Unknown Source:0)
	at me.rhunk.snapenhance.core.SnapEnhance$init$3.invokeSuspend(Unknown Source:189)
	at w2.a.resumeWith(Unknown Source:8)
	at V2.s.s(Unknown Source:6)
	at Q2.a.resumeWith(Unknown Source:22)
	at w2.a.resumeWith(Unknown Source:31)
	at V2.s.s(Unknown Source:6)
	at Q2.a.resumeWith(Unknown Source:22)
	at w2.a.resumeWith(Unknown Source:31)
	at Q2.H.run(Unknown Source:114)
	at Q2.S.U(Unknown Source:140)
	at Q2.B.y(Unknown Source:104)
	at Q2.B.z(Unknown Source:2)
	at me.rhunk.snapenhance.core.SnapEnhance.init(SourceFile:6)
	at me.rhunk.snapenhance.core.XposedLoader.handleLoadPackage$lambda$0(Unknown Source:17)
	at me.rhunk.snapenhance.core.XposedLoader.a(Unknown Source:0)
	at me.rhunk.snapenhance.common.messaging.a.invoke(Unknown Source:148)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at f.IWmP.CUTtre.bpjVIM.K.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:180)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1159)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1260)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6690)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
```


### Snapchat Version

13.21.0.43

### SnapEnhance Version

2.1.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by Flole998** [comment]
This was caused by installing the wrong version (armv7 vs. armv8). Is there any reason why it's not a single build? If yes there should be a warning if accidentally the wrong version is selected. A "file not found" for the library strongly points towards an unsupported arch being used.

**Comment by Flole998** [comment]
I switched ROMs and before I had a 32 bit ROM, now 64 bit but I wasn't aware that this refers to 32/64 bit and by switching ROMs I also need the other build.

**Comment by Flole998** [comment]
Old device, stock rom is/was 32 bit, lineage os rom is 64 bit. And normally it doesn't matter as all other apps have a single apk with all supported archs in them, this app is the only reason I noticed that it changed.
