### ISSUE TITLE
bug: not hooking after update

### ISSUE THREAD

**Issue by VxlerieUwU** [rhunk/SnapEnhance#306]
### Description

When updating to latest snapchat, SnapEnhance breaks completely. I have tried clearing mappings, to no sucess. It appears that SnapEnhance isn't able to hook to Snapchat to generate its mappings

### Reproduction steps

1. Update to latest snapchat
2. Open snapchat
3. SnapEnhance dissapears

### Logs

```markdown
[ 2023-10-05T09:00:20.918    10386: 25492: 25492 I/LSPosed-Bridge  ]   Loading class me.rhunk.snapenhance.XposedLoader                                  [ 2023-10-05T09:00:21.760    10395: 25463: 25463 I/LSPosed-Bridge  ] UI thread runnable failed                                                          [ 2023-10-05T09:00:21.761    10395: 25463: 25463 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference                                                                          at android.view.LayoutInflater.from(LayoutInflater.java:288)                                                                                            at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:184)                                                                      at com.android.internal.app.AlertController$AlertParams.<init>(AlertController.java:1106)                                                               at android.app.AlertDialog$Builder.<init>(AlertDialog.java:500)                                                                                         at me.rhunk.snapenhance.ui.ViewAppearanceHelper.newAlertDialogBuilder(ViewAppearanceHelper.kt:96)                                                       at me.rhunk.snapenhance.manager.impl.MappingManager$init$3.invoke(MappingManager.kt:74)                                                                 at me.rhunk.snapenhance.manager.impl.MappingManager$init$3.invoke(MappingManager.kt:73)                                                                 at me.rhunk.snapenhance.ModContext.runOnUiThread$lambda$1(ModContext.kt:59)                                                                             at me.rhunk.snapenhance.ModContext.$r8$lambda$e0eoznY0V2EQZ6vWnVGOfSU6aLw(Unknown Source:0)                                                             at me.rhunk.snapenhance.ModContext$$ExternalSyntheticLambda2.run(Unknown Source:2)                                                                      at android.os.Handler.handleCallback(Handler.java:942)                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)                                                                                                  at android.os.Looper.loopOnce(Looper.java:201)                                                                                                          at android.os.Looper.loop(Looper.java:288)                                                                                                              at android.app.ActivityThread.main(ActivityThread.java:7936)                                                                                            at java.lang.reflect.Method.invoke(Native Method)                                                                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
```

### Snapchat Version

12.54.0.67

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
hello, I might have fixed the bug, could you test latest CI build please?
