### ISSUE TITLE
bug: can't change the preview and camera resolution

### ISSUE THREAD

**Issue by hamzaharoon1314** [rhunk/SnapEnhance#369]
### Description

When we try to change any resolution more than 1920x1080 the Snapchat app crashes.
I'm on Snapchat Stable Version with 1.2.5 Module.

### Reproduction steps

When we change resolution in SnapEnhance for camera than Snapchat app crashes.

### Logs

```markdown
----part 4 start----

[2023-11-01T02:20:42.765 10410: 19209: 19209 I/LSPosed- Bridge Loading legacy module me.rhunk.snapenhance from /

data/app/--EA2p1Gc05Vryj-Kae5GnGg==/me.rhunk. snapenhance- Ec3QcT4FSPjf8MThCRHmUA==/base.apk

[2023-11-01T02:20:42.846 10410: 19209: 19209 I/ LSPosed-Bridge ] Loading class me.rhunk.snapenhance.XposedLoader

[2023-11-01T02:20:43.534 10410: 19209: 19269 I/LSPosed-

Bridge Crash unexpectedly: java.lang.IllegalArgumentException: Preview resolution Resolution (width=3264, height=2448) not supported for DEFAULT + FAST

at p3e.z(SourceFile:1)

at MP1.b(SourceFile:77) at MP1.a(SourceFile:186)

at Owf.1(SourceFile:52)

at OWf.k(SourceFile:9)

at Di9.a(SourceFile:146)

at U92.n(SourceFile:40)

at U92.m(SourceFile:155)

at f32.f(SourceFile:83)

at e32.invoke(SourceFile:41)

at Ry0.invoke(SourceFile:53)

at yQ1.onOpened(SourceFile:29)

at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceIm pl.java:180)

at QP1.run(SourceFile:19)

at android.os.Handler.handleCallback (Handler.java:942)

at android.os.Handler.dispatchMessage(Handler.java:99)

at Ue2.dispatchMessage(SourceFile:7)

at android.os.Looper.loopOnce (Looper.java:201) at android.os.Looper.loop(Looper.java:288)

at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Snapchat Version

12.57.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
This is most likely a device issue, we don't own any devices on which it doesn't work so if someone is willing to investigate feel free to do so and let us know here.
