### ISSUE TITLE
Crash on open Friend Feed Menu

### ISSUE THREAD

**Issue by Ch0nkst3r** [rhunk/SnapEnhance#657]
### Description

When having activated some of the options under "Friend Feed Menu Buttons" and long pressing on a friend, Snapchat just chrashes.

### Reproduction steps

1. Go to User Interface -> Fried Feed Menu Buttons
2. Click on Stealth Mode & Unsavable Messages
3. Save
4. Long press on any friend in Snapchat
5. Crash

### Logs

```markdown
FATAL EXCEPTION: main
Process: com.snapchat.android, PID: 12409
java.lang.IllegalStateException: No conversation found
	at me.rhunk.snapenhance.core.ui.menu.impl.FriendFeedInfoMenu.getCurrentConversationInfo(Unknown Source:130)
	at me.rhunk.snapenhance.core.ui.menu.impl.FriendFeedInfoMenu.inject(Unknown Source:46)
	at me.rhunk.snapenhance.core.ui.menu.MenuViewInjector$asyncOnActivityCreate$1.invoke$lambda$1(Unknown Source:51)
	at me.rhunk.snapenhance.core.ui.menu.MenuViewInjector$asyncOnActivityCreate$1.b(Unknown Source:0)
	at me.rhunk.snapenhance.core.ui.menu.a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

### Snapchat Version

12.71.0.30

### SnapEnhance Version

2.0.0 Build d8d4f49

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Can't reproduce
