### ISSUE TITLE
Failed to initialize bridge

### ISSUE THREAD

**Issue by reveh2** [rhunk/SnapEnhance#670]
### Description

SE fails to load on startup with a "failed to initialize bridge" error. 
Logging out of an account and logging back in is the only way to load SE without an error. Every time I close Snapchat this error repeats and SE fails to load.
c16af14 is the last beta build without this issue occurring.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs

```markdown
|V/2024-02-09 22:17:36/manager/Loading RemoteSideContext
|V/2024-02-09 22:17:37/core/reloading config
|E/2024-02-09 22:17:37/core/Failed to initialize bridge
|E/2024-02-09 22:17:37/core/java.util.NoSuchElementException: Array contains no element matching the predicate.
	at me.rhunk.snapenhance.core.SnapEnhance.initNative(Unknown Source:140)
	at me.rhunk.snapenhance.core.SnapEnhance.init(Unknown Source:35)
	at me.rhunk.snapenhance.core.SnapEnhance.access$init(Unknown Source:0)
	at me.rhunk.snapenhance.core.SnapEnhance$1$2$1$2$3$1$1.invokeSuspend(Unknown Source:15)
	at L1.a.resumeWith(Unknown Source:8)
	at e2.I.run(Unknown Source:114)
	at e2.T.V(Unknown Source:138)
	at e2.B.L0(Unknown Source:104)
	at e2.B.M0(Unknown Source:2)
	at me.rhunk.snapenhance.core.SnapEnhance$1$2$1$2.invoke(SourceFile:9)
	at me.rhunk.snapenhance.core.SnapEnhance$1$2$1$2.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.bridge.BridgeClient.connect(Unknown Source:159)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:7)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:179)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

|I/2024-02-09 22:17:48/FA/App measurement disabled via the manifest
|I/2024-02-09 22:17:48/FA/App measurement initialized, version: 83006
|I/2024-02-09 22:17:48/FA/To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
|I/2024-02-09 22:17:48/FA/To enable faster debug mode event logging run:
  adb shell setprop debug.firebase.analytics.app com.snapchat.android
```

### Snapchat Version

12.70.0.34

### SnapEnhance Version

2.0.0 every build after c16af14

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
@reveh2 can you provide the Android version of the device?

**Comment by reveh2** [comment]
> @reveh2 can you provide the Android version of the device?

Android 9

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/a75193074280dbd34b1a6b79c91354da61430f62
