### ISSUE TITLE
Features not working

### ISSUE THREAD

**Issue by Nnaemsy** [rhunk/SnapEnhance#781]
### Description

This message keeps popping up every time I open the app. Which from experience from the last stable release, doesn't let u have access to all the features enabled
![Screenshot_20240326_172936_Snapchat](https://github.com/rhunk/SnapEnhance/assets/161165813/e32c1481-d5c6-4a5b-a648-e7f5e6504910)
[snapenhance-logs-1711488677344.zip](https://github.com/rhunk/SnapEnhance/files/14764871/snapenhance-logs-1711488677344.zip)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs

```markdown
android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:261)
	at android.content.res.Resources.getDimensionPixelSize(Resources.java:889)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:158)
	at LSPHooker_.getDimensionPixelSize(Unknown Source:15)
	at me.rhunk.snapenhance.core.util.ktx.AndroidExtKt.getDimens(Unknown Source:16)
	at me.rhunk.snapenhance.core.features.impl.ui.FriendFeedMessagePreview.onActivityCreate(Unknown Source:84)
	at me.rhunk.snapenhance.core.features.FeatureManager$onActivityCreate$1$1.invoke(SourceFile:2)
	at me.rhunk.snapenhance.core.features.FeatureManager$onActivityCreate$1$1.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.features.FeatureManager.initFeatures(Unknown Source:35)
	at me.rhunk.snapenhance.core.features.FeatureManager.onActivityCreate(Unknown Source:11)
	at me.rhunk.snapenhance.core.SnapEnhance.onActivityCreate(Unknown Source:15)
	at me.rhunk.snapenhance.core.SnapEnhance.access$onActivityCreate(Unknown Source:0)
	at me.rhunk.snapenhance.core.SnapEnhance$2.invoke(SourceFile:6)
	at me.rhunk.snapenhance.core.SnapEnhance$2.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.SnapEnhance$hookMainActivity$2.invoke(SourceFile:4)
	at me.rhunk.snapenhance.core.SnapEnhance$hookMainActivity$2.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.util.hook.Hooker$newMethodHook$3.afterHookedMethod(Unknown Source:30)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(XposedBridge.java:430)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:192)
	at LSPHooker_.onCreate(Unknown Source:11)
	at androidx.core.app.ComponentActivity.onCreate(Unknown Source:0)
	at androidx.fragment.app.FragmentActivity.onCreate(SourceFile:18)
	at com.snap.taskexecution.scoping.recipes.ScopedFragmentActivity.onCreate(SourceFile:75)
	at android.app.Activity.performCreate(Activity.java:8975)
	at android.app.Activity.performCreate(Activity.java:8944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Snapchat Version

12.80.0.37

### SnapEnhance Version

2.00

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Use Stable version Of Snapchat 
The current latest is v12.79.0.37

**Comment by Nnaemsy** [comment]
Yes, thanks it works now. My bad
