### ISSUE TITLE
Snapchat can't connect with snapenhance 

### ISSUE THREAD

**Issue by Brownlad-360** [rhunk/SnapEnhance#848]
### Description

It happened when my phone battery died and when I restarted it, and this error came in referring to update the snapenhance even so its already the latest v2 buil
![Screenshot_20240409_232325_Snapchat](https://github.com/rhunk/SnapEnhance/assets/145240277/6a5cdc9a-8167-4c11-a5a3-8762e21b526f)
d. Idk how solve this

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1936)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2071)
	at me.rhunk.snapenhance.core.bridge.BridgeClient.connect(Unknown Source:150)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:7)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1233)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1565)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1502)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7553)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

_No response_

### Snapchat Version

12.80.1.0

### SnapEnhance Version

2.0.0

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
What Ci Run are you using ?

**Comment by bocajthomas** [comment]
> ### Description
> It happened when my phone battery died and when I restarted it, and this error came in referring to update the snapenhance even so its already the latest v2 buil ![Screenshot_20240409_232325_Snapchat](https://private-user-images.githubusercontent.com/145240277/321004986-6a5cdc9a-8167-4c11-a5a3-8762e21b526f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTkzMTQsIm5iZiI6MTcxMjY5OTAxNCwicGF0aCI6Ii8xNDUyNDAyNzcvMzIxMDA0OTg2LTZhNWNkYzlhLTgxNjctNGMxMS1hNWEzLTg3NjJlMjFiNTI2Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQyMTQzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTRmMzQyMTE5YzcxMjJlNTJkYmE1ZjkxMmQ2NzIzYjVlNzk4OGExNmUxMzYwM2Q1NmYwNjRhNTRhNzEzNTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7ucbgSesYP77amjiKpUsULnF9wN38OSluYq7O1Pjr_w) d. Idk how solve this
> 
> ### Reproduction steps
> 1. Go to `...`
> 2. Click on `....`
> 3. Scroll down to `....`
> 4. See error.
> 
> ### Logs
> java.util.concurrent.TimeoutException at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1936) at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2071) at me.rhunk.snapenhance.core.bridge.BridgeClient.connect(Unknown Source:150) at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:7) at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:1) at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12) at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404) at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152) at LSPHooker_.attach(Unknown Source:11) at android.app.Instrumentation.newApplication(Instrumentation.java:1233) at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1565) at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1502) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7553) at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:226) at android.os.Looper.loop(Looper.java:313) at android.app.ActivityThread.main(ActivityThread.java:8757) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
> 
> _No response_
> 
> ### Snapchat Version
> 12.80.1.0
> 
> ### SnapEnhance Version
> 2.0.0
> 
> ### Agreement
> * [ ]  This is not a bug regarding Snapchat+.
> * [x]  I have provided a detailed description of the issue.
> * [ ]  I have attached a log if deemed neccessary.
> * [x]  This issue is not a duplicate.

Are you using the PreRelease or A Ci Run ?
