### ISSUE TITLE
Snapchat can't connect to the SnapEnhance app

### ISSUE THREAD

**Issue by jbro129** [rhunk/SnapEnhance#875]
### Description

I installed the new version, enabled the module in lsp, rebooted my phone, opened the app and only enabled amoled dark theme, then opened Snapchat and saw the message "Snapchat can't connect to the SnapEnhance app".

### Reproduction steps

Upon opening snapchat after rebooting after enabling the module in LSPosed.

### Logs

```markdown
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1936)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2071)
	at me.rhunk.snapenhance.core.bridge.BridgeClient.connect(Unknown Source:150)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:7)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at ZBsqSk.k.iYWXJqhOXfyIA.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:179)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1283)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1512)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1449)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7625)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by jbro129** [comment]
Even after resetting the config the message remains.

**Comment by bocajthomas** [comment]
Root Or Non Root ?

**Comment by jbro129** [comment]
> Root Or Non Root ?

Rooted with magisk v27.0 and using LSPosed v1.9.2.

**Comment by Anashanif8091** [comment]
Non root

**Comment by bocajthomas** [comment]
> > Root Or Non Root ?
> 
> Rooted with magisk v27.0 and using LSPosed v1.9.2. Samsung s23 Ultra running android 14.

@authorisation idk Root 🤣

**Comment by conors06** [comment]
Using non root with the latest version from release and snapcbat new update and  getting this error as well. java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1936)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2071)
	at me.rhunk.snapenhance.core.bridge.BridgeClient.connect(Unknown Source:150)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:7)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleBefore(XposedBridge.java:404)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(LSPosedBridge.java:152)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1283)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1512)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1449)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7625)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
