### ISSUE TITLE
App stuck on splash screen...

### ISSUE THREAD

**Issue by pravinnirmal** [rhunk/SnapEnhance#978]
### Description

App was working fine for almost a month. After security patch update in Pixel experience rom i am unable to open app. I tried reinstalling snap enhance even in older 11.75v of SC also after patching app is stuck in splash screen.

I am not sure if this but is based on security patch update or not. But many users have reported the same in telegram.

### Reproduction steps

1. Patch app.
2. open app.
5. See error.

### Logs

```markdown
time: 1714393726254
msg: java.lang.ClassNotFoundException: Didn't find class "com.snap.snapchat.shell.MushroomAppShell" on path: DexPathList[[zip file "/data/app/~~bQWsQG8N-kkQXaBmtKupEg==/com.snapchat.android-Gyx-T4BRQ-PJmvYqq0cUkA==/base.apk"],nativeLibraryDirectories=[/data/app/~~bQWsQG8N-kkQXaBmtKupEg==/com.snapchat.android-Gyx-T4BRQ-PJmvYqq0cUkA==/lib/arm64, /data/app/~~bQWsQG8N-kkQXaBmtKupEg==/com.snapchat.android-Gyx-T4BRQ-PJmvYqq0cUkA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
stacktrace: java.lang.RuntimeException: Unable to instantiate application com.snap.snapchat.shell.MushroomAppShell package com.snapchat.android: java.lang.ClassNotFoundException: Didn't find class "com.snap.snapchat.shell.MushroomAppShell" on path: DexPathList[[zip file "/data/app/~~bQWsQG8N-kkQXaBmtKupEg==/com.snapchat.android-Gyx-T4BRQ-PJmvYqq0cUkA==/base.apk"],nativeLibraryDirectories=[/data/app/~~bQWsQG8N-kkQXaBmtKupEg==/com.snapchat.android-Gyx-T4BRQ-PJmvYqq0cUkA==/lib/arm64, /data/app/~~bQWsQG8N-kkQXaBmtKupEg==/com.snapchat.android-Gyx-T4BRQ-PJmvYqq0cUkA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1474)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7268)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.snap.snapchat.shell.MushroomAppShell" on path: DexPathList[[zip file "/data/app/~~bQWsQG8N-kkQXaBmtKupEg==/com.snapchat.android-Gyx-T4BRQ-PJmvYqq0cUkA==/base.apk"],nativeLibraryDirectories=[/data/app/~~bQWsQG8N-kkQXaBmtKupEg==/com.snapchat.android-Gyx-T4BRQ-PJmvYqq0cUkA==/lib/arm64, /data/app/~~bQWsQG8N-kkQXaBmtKupEg==/com.snapchat.android-Gyx-T4BRQ-PJmvYqq0cUkA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1346)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
	... 11 more
```

### Snapchat Version

12.84.0.40

### SnapEnhance Version

2.0.2

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by Ch0nkst3r** [comment]
What LSPatch Version did you use?

**Comment by TheVisual** [comment]
LSPatch is dead please use a fork unfixable on are end.

For Root:
https://github.com/mywalkb/LSPosed_mod

For No Root:
https://github.com/HSSkyBoy/NPatch

**Comment by pravinnirmal** [comment]
> LSPatch is dead please use a fork unfixable on are end.
> 
> For Rooted: [LSPosed mod](https://github.com/mywalkb/LSPosed_mod)
> 
> For Unrooted / Non Root: [NPatch](https://github.com/HSSkyBoy/NPatch)

How to download NPatch there is no release?

**Comment by bocajthomas** [comment]
> Thanks for your help. I have installed NPatch successfully but once patching with core app and trying to install apk i am getting `INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl208790651.tmp/base.apk (at Binary XML file line #8): Requires development platform 28 but this is a release platform.` error

What android version are you running?
What's you're API level ?

**Comment by pravinnirmal** [comment]
> > Thanks for your help. I have installed NPatch successfully but once patching with core app and trying to install apk i am getting `INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl208790651.tmp/base.apk (at Binary XML file line #8): Requires development platform 28 but this is a release platform.` error
> 
> What android version are you running? What's you're API level ?

Android version 14. 
API version i am not sure where to find but in NPatch app it is showing as 93.

**Comment by bocajthomas** [comment]
> Android version 14. API Level: 34.

NPatch is for Android 15 
That's why.
you can use LSPatch On A14

**Comment by pravinnirmal** [comment]
I was using LsPatch only previously but i got the above issue.

**Comment by bocajthomas** [comment]
> I was using LsPatch only previously but i got the above issue.

It's nothing to do with the patches idk why @TheVisual even mentioned it

**Comment by pravinnirmal** [comment]
> > I was using LsPatch only previously but i got the above issue.
> 
> It's nothing to do with the patchers idk why @TheVisual even mentioned it

Ya i am not sure what to do now. Any idea on the error looks like some class file is missing. Can we unpack and repack apk any possibilities like that?

**Comment by bocajthomas** [comment]
> Ya i am not sure what to do now. Any idea on the error looks like some class file is missing. Can we unpack and repack apk any possibilities like that?

Can you test the Google play Snapchat
# links
> - [LSPatch](https://github.com/LSPosed/LSPatch)<br/>
> - [SAI](https://github.com/Aefyr/SAI)<br/>
> - [Snapchat(Google play)](https://play.google.com/store/apps/details?id=com.snapchat.android)<br/>

<details closed>
 <summary> Installation Guide (LSPatch & SAI) ( Best For New Users )</summary>

<details closed> 
   <summary>What's Needed</summary>
  
>   - SnapEnhance<br/>
>   - LSPatch<br/> 
>   - SAI<br/>
>   - Snapchat From Google Play<br/>
</details>

<details closed>
  <summary> LSPatch Patching Guide</summary>

  1. Open " LSPatch " 
(It Should Say Shizuku Is Not Running This Is Fine)
  2. Press The " Manage " Tab
  3. Press The " Plus " Icon 
  4. Press " Select An Installed App "
  5. Find Snapchat (You Can Do This By search or scrolling) 
  6. Press Snapchat 
  7. Press " Intergrated "
  8. Press " Embed Modules "
  9. Press " Select apk(s) From Storage "
  10. Find " SnapEnhance " You Just Download 
  11. Press " Start Patch "
  12. Wait For " LSPatch " To Patch Snapchat
  13. Now Follow " SAI Installation Guide " 
 </details>


<details closed>
   <summary> SAI Installation Guide</summary>

  16. Open " SAI " 
  17. Press " Install Apks "
  18. Press " System File Picker "
  19. Select all 4 apks That Have Just Been Patched 
  20. Press " Install "
  21. Now Follow " SnapEnhance Setup Guide  "
</details>

<details closed >
  <summary>SnapEnhance Setup Guide</summary>

  1. Open SnapEnhance 
  2. Set Your Language ( If Supported )
  3. Press " > "
  4. Allow All Requests 
  5. Press " Select Folder "
  6. Create A Folder For SnapEnhance ( This Will Allow SnapEnhance To Read And Write )
  7. Press " > "
  8. Press " Generate "
  9. Wait For It To Map 
  10. Press " Ok "
  11. Press " Tick "
</details>
</details>

**Comment by pravinnirmal** [comment]
> > Ya i am not sure what to do now. Any idea on the error looks like some class file is missing. Can we unpack and repack apk any possibilities like that?
> 
> Can you test the Google play Snapchat i think its something to do with the snapchat apk/app and not the patchers
> 
> # links
> > * [LSPatch](https://github.com/LSPosed/LSPatch)
> > * [SAI](https://github.com/Aefyr/SAI)
> > * [Snapchat(Google play)](https://play.google.com/store/apps/details?id=com.snapchat.android)
> 
> Installation Guide (LSPatch & SAI) ( Best For New Users )
> What's Needed
> > * SnapEnhance
> > * LSPatch
> > * SAI
> > * Snapchat From Google Play
> 
> LSPatch Patching Guide
> 1. Open " LSPatch "
>    (It Should Say Shizuku Is Not Running This Is Fine)
> 2. Press The " Manage " Tab
> 3. Press The " Plus " Icon
> 4. Press " Select An Installed App "
> 5. Find Snapchat (You Can Do This By search or scrolling)
> 6. Press Snapchat
> 7. Press " Intergrated "
> 8. Press " Embed Modules "
> 9. Press " Select apk(s) From Storage "
> 10. Find " SnapEnhance " You Just Download
> 11. Press " Start Patch "
> 12. Wait For " LSPatch " To Patch Snapchat
> 13. Now Follow " SAI Installation Guide "
> 
> SAI Installation Guide
> 16. Open " SAI "
> 17. Press " Install Apks "
> 18. Press " System File Picker "
> 19. Select all 4 apks That Have Just Been Patched
> 20. Press " Install "
> 21. Now Follow " SnapEnhance Setup Guide  "
> 
> SnapEnhance Setup Guide

Google play snapchat is working normally but once patched it is not working.

**Comment by pravinnirmal** [comment]
> That's because LSPosed and LSPatch is broken on Android 14 QPR2. You probably get QPR2 update.
> 
> If NPatch didn't worked, then there is nothing to do i think.

Yes i too think so. Will try to roll back or else have to  wait for any kind devs that will fix this issue if possible.

**Comment by nikhilpanchal1** [comment]
I'm on android 15 beta 2, using snapchat from playstore. Using Npatch and got this error while trying to install with core.apk - INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl826143725.tmp/base.apk (at Binary XML file line #8): Requires development platform 28 (current platform is any of [VanillaIceCream])

**Comment by suryadip2008** [comment]
> I'm on android 15 beta 2, using snapchat from playstore. Using Npatch and got this error while trying to install with core.apk - INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl826143725.tmp/base.apk (at Binary XML file line #8): Requires development platform 28 (current platform is any of [VanillaIceCream])

**Android 15 is not supported yet!**
